import Head from 'next/head';
export default function Dashboard() {
    return (
        <div>
            <Head>
                <title>dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </div>
    )
}
