import Head from "next/head";
import LoginPage from "../components/login/login";
export default function Login() {
    return (
        <div>
            <Head>
                <title>login page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <LoginPage/>
        </div>
    )
}